AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'db/migrate/**/*'
    - 'db/schema.rb'
    - 'vendor/**/*'

require:
  - rubocop-rails
  - rubocop-capybara

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 30
